enableGlobalVirtualStore: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.fcca21bee9fa82419c9d0d85541393bf7dd2cace
  vite-plus: 0.0.0-commit.fcca21bee9fa82419c9d0d85541393bf7dd2cace
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
